version: '3.7'
networks:
  nx-network:
    ipam:
      config:
        - subnet: '172.6.0.0/16'

volumes:
  nx-postgres-volume:
    external: true

services:
  nx-postgres:
    image: endykaufman/postgres-default
    container_name: nx-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - nx-postgres-volume:/var/lib/postgresql/data
    networks:
      - nx-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}']
      interval: 5s
      timeout: 5s
      retries: 5

  nx-api:
    image: node:16-alpine
    user: ${CURRENT_UID}
    container_name: nx-api
    environment:
      - POSTGRES_HOST=nx-postgres
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nx-postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    working_dir: '/app'
    volumes:
      - ./../../:/app
    networks:
      - nx-network
    command: 'node ./dist/apps/api/main.js'
    tty: true
    depends_on:
      - nx-postgres
