version: '3.7'

networks:
  nxnest:
    ipam:
      config:
        - subnet: '172.6.0.0/16'

volumes:
  nxnest-postgres-volume:
    external: true

services:
  nxnest-postgres:
    image: endykaufman/postgres-default
    container_name: nxnest-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - nxnest-postgres-volume:/var/lib/postgresql/data
    networks:
      - nxnest
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  nxnest-api:
    image: node:16-alpine
    user: ${CURRENT_UID}
    container_name: nxnest-api
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: '/app'
    volumes:
      - ./../:/app
    networks:
      - nxnest-network
    command: 'npm run start'
    tty: true
    depends_on:
      - nxnest-postgres
